### ISSUE TITLE
Publish webWW library to node package manager (npm)

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#136]
Web WorldWind will be included as a package in npm. This will provide developers a convenient way to acquire the most up-to-date version of Web WorldWind without the need of manually building the library through Grunt after downloading the whole repository.

- [x] Test concept in mockup (personal GitHub/npm registry) (#139) 
- [x] Expose a CommonJS (module.exports) interface (#151)
- [x] Establish an organization in npm registry for the project (#150)
- [x] Test npm package in Webpack-based project (#157)
- [x] Test npm package in Browserify-based project (#158)
- [x] Enable local images in NPM package (#164)
- [x] Review npm package version updating to set the stage for CI tests (#145)
- [x] Deploy npm package via CI (#152)
- [x] Consider nightly/snapshot npm packages (#141)

The aforementioned points rely on work described in issues #148 (build improvements) and #144 (Travis CI integration).

**Comment by Beak-man** [comment]
@zglueck pointed me towards https://unpkg.com. Every package in npm can be published via a CDN with this. Worthwhile to check it out when it comes to publish the library in a CDN.

**Comment by pdavidc** [comment]
@Beak-man Thanks for keeping the team in the loop on this. It's absolutely an option we can consider.
