### ISSUE TITLE
Build process review: Library build improvement

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#148]
Modify and streamline (where applicable) the building process for the library. Besides having a positive impact on the project on its own, this will benefit integration with the Travis CI environment (i.e. faster builds), and will also set the stage for any modifications needed in the build process to expose the library as an npm package. Required for work in #136 

- [x] Review and continue work on branch feature/build_suggestions #143 
- [ ] Optimize requireJS task. It’s currently done twice. #146
- [x] Investigate whether external libraries in src/util can be refactored as npm dependencies #147

**Comment by pdavidc** [comment]
Closing in favor of epic #537
