### ISSUE TITLE
Text outline control

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#173]
Applications need the capability to make text labels visible over the map background. Text outlines provide this capability and is usable with any combination of light/dark text and light/dark backgrounds. Supersedes #97 

Enhance text outline control by extending TextAttributes with the following properties:
- Outline enable bit
- Outline width
- Outline color

- [x] Refactor TextSupport as TextRenderer #176 
- [x] Consider decoupling text line wrapping functions into a new utility class #424 
- [x] Basic text outline attributes #178 
- [x] TextRender color support #174
- [x] Text outline color #175 
- [x] Reflect text attribute changes #177
