### ISSUE TITLE
Update Web WorldWind documentation

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/WebWorldWind#187]
Update the overall documentation in the Web WorldWind's repository. 

1) Add several new files which outline the project's contribution guidelines. It is designed for both the WorldWind team and any users who wish to open an issue or pull request in the Web WorldWind repository. 

2) Make "WorldWind" the name standard (as opposed to "World Wind"). This will ensure that the project name is consistent with the [website](https://worldwind.arc.nasa.gov/) and all other project repositories. 

Implementation stories: 

- [x] Add CONTRIBUTING.md [(#188)](https://github.com/NASAWorldWind/WebWorldWind/issues/188)
- [x] Add ISSUE_TEMPLATE.md [(#189)](https://github.com/NASAWorldWind/WebWorldWind/issues/189)
- [x] Add PR_TEMPLATE.md [(#190)](https://github.com/NASAWorldWind/WebWorldWind/issues/190)
- [x] Make "WorldWind" the name standard [(#191)](https://github.com/NASAWorldWind/WebWorldWind/issues/191)
