### ISSUE TITLE
Implement content hosting service at Ames

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#199]
This epic covers the tasks required to stand up a content hosting service at Ames. The service should provide the WorldWind team the ability to host production artifacts for users. Primarily this will be javascript libraries and resources but may also include assets from other projects.

- [x] Investigate dynamic content retrieval options #195 
- [x] Conceptual mock-up and risk analysis #196
- [x] Secure content hosting infrastructure #194
- [x] Review Artifactory run configuration #221 
- [x] Review server header configuration #198 
- [x] Review Artifactory version update #223

**Comment by pdavidc** [comment]
@zglueck This looks done. Does anything need my review?

**Comment by zglueck** [comment]
@pdavidc it is indeed complete and awaiting review.

The reviewable content of the epic would be the Apache configuration and Artifactory file layout on the server.

**Comment by zglueck** [comment]
@RandolphKim reviewed the Apache configuration and we discussed the service layout and operation.
